apiVersion: apps/v1
kind: Deployment
metadata:
  name: learninghubmoodledev
  namespace: learninghubmoodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learninghubmoodledev
  template:
    metadata:
      labels:
        app: learninghubmoodledev
    spec:
      containers:
      - name: learninghubmoodleimage
        image: learninghubmoodlecrdev.azurecr.io/learninghubmoodleimage:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: moodledata
          mountPath: /var/www/moodledata
          readOnly: false
        - name: moodletheme
          mountPath: /var/www/html/theme
      volumes:
      - name: moodledata
        persistentVolumeClaim:
          claimName: moodledataclaim
      - name: moodletheme
        persistentVolumeClaim:
          claimName: moodlethemeclaim