apiVersion: apps/v1
kind: Deployment
metadata:
  name: learninghubmoodleeintegrity
  namespace: learninghubmoodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learninghubmoodleeintegrity
  template:
    metadata:
      labels:
        app: learninghubmoodleeintegrity
    spec:
      containers:
      - name: learninghubmoodleimage
        image: learninghubmoodlecreintegrity.azurecr.io/learninghubmoodleimage:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 4Gi
          limits:
            cpu: 1
            memory: 8Gi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: moodledata
          mountPath: /var/www/moodledata
          readOnly: false
        - name: moodletheme
          mountPath: /var/www/html/theme
      volumes:
      - name: moodledata
        azureFile:
          secretName: azure-storage-secret
          shareName: moodledata
          readOnly: false
          mountOptions:
            - uid=33
            - gid=33
            - dir_mode=0770
            - file_mode=0660
            - mfsymlinks
            - nobrl
      - name: moodletheme
        persistentVolumeClaim:
          claimName: moodlethemeclaim