apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: moodledata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-moodle
  csi:
    driver: file.csi.azure.com
    volumeHandle: "moodleCluster#learninghubmoodleeintegrity#moodledata"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: moodledata
      server: lhmoodleeintegrity.privatelink.file.core.windows.net
    nodeStageSecretRef:
      name: azure-secret
      namespace: learninghubmoodle