apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: moodledata
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: "moodleCluster#learninghubmoodledev#moodledata"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: moodledata
      server: learninghubmoodledev.privatelink.file.core.windows.net
    nodeStageSecretRef:
      name: azure-secret
      namespace: learninghubmoodle
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks