apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledataclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi
  volumeName: moodledata