apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodlethemeclaim
  namespace: learninghubmoodle
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi
  volumeName: moodletheme