apiVersion: v1
kind: Service
metadata:
  name: learninghubmoodle-service
  namespace: learninghubmoodle
spec:
  selector:
    app: learninghubmoodlepgvle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer