apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-moodle
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
mountOptions:
  - uid=33
  - gid=33
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - actimeo=30
  - cache=none
reclaimPolicy: Retain
volumeBindingMode: Immediate
